version: "3"
services:
  database:
    image: postgres:14
    container_name: postgresql
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
